version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd Api-Gateway
      - mvn test
      - echo Build completed on `date`
      - mvn package
      - docker build -t Api-Gateway .
