version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd Eureka-server
      - mvn test
      - echo Build completed on `date`
      - mvn package
      - docker build -t Eureka-server .
