version: "3.3"
services:
  
  Eureka-server:
      build: Eureka-server
      ports:
        - 8761:8761
      environment:
        REGISTRY_URL: http://localhost:8761/eureka

  Api-Gateway:
      build: Api-Gateway
      ports:
        - 8010:8010
      environment:
        REGISTRY_URL: http://localhost:8761/eureka

  Billing-service:
      build: Billing-service
      ports:
        - 8011:8011
      environment:
        REGISTRY_URL: http://localhost:8761/eureka

  Monitoring-service:
      build: Monitoring-service
      ports:
        - 8012:8012
      environment:
        REGISTRY_URL: http://localhost:8761/eureka


        