server:
  port: 8012
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: monitoring-service
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.catalog.one.monitoring: DEBUG