
DROP TABLE IF EXISTS MONITORING_TRANSACTION ;
DROP TABLE IF EXISTS MONITORING_TRANSACTION_DETAILS ;



create table MONITORING_TRANSACTION (
    ID int NOT NULL AUTO_INCREMENT,
    MICROSERVICE_NAME varchar(100) NOT NULL ,
    STATUS varchar(6) NOT NULL UNIQUE,
    PRIMARY KEY (ID),
);

create table MONITORING_TRANSACTION_DETAILS (
    TRANSACTION_ID int NOT NULL AUTO_INCREMENT,
    MICROSERVICE_ID int NOT NULL,
    DOWN_TIME DATE ,
    UP_TIME TIMESTAMP,
    PRIMARY KEY (TRANSACTION_ID),
);
