version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd Monitoring-Service
      - mvn test
      - echo Build completed on `date`
      - mvn package
      - docker build -t Monitoring-Service .
