version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd Billling-Service
      - mvn test
      - echo Build completed on `date`
      - mvn package
      - docker build -t Billing-Service .
